Bug fix - Owner tokens not updated on token transfer
Vault-Hill/VLAND pull request #5
Opened 2022-01-07 12:04 UTC by jmulq

Fixes #3.

Add solhint and prettier for solidity.

Add unit tests to source control.

2022-01-07 12:13 UTC, UmairJanjua6 commented on contracts/VLAND.sol
> +        uint256 maxSupply_
As we have fix total supply, so it's better to define it at storage level

2022-01-07 12:15 UTC, UmairJanjua6 commented on contracts/VLAND.sol
> +    function maxSupply() external view returns (uint256) {
renaming maxSupply to totalSupply is better as many new platforms are only reading the totalSupply function now

2022-01-07 13:19 UTC, UmairJanjua6 commented on contracts/VLAND.sol
>      function tokenURI(uint256 tokenId) public view virtual override returns (string memory) {
If we are going to use the token ID in tokenURI then we just have to concatenate the token ID with the base URI, no need to write the extra code

2022-01-09 19:57 UTC, UmairJanjua6 commented on test/VLAND.test.js
> +        it('revokeRole emits an event if successful', async () => {
poping up the error of invalid address

2022-01-09 20:01 UTC, UmairJanjua6 requested changes
owner tokens function is working fine now. But there is some [issue](https://ibb.co/cNqJGP5) in test cases of assigning minter, admin roles (working perfect on-chain).

2022-01-17 11:12 UTC, jmulq commented
> owner tokens function is working fine now. But there is some [issue](https://ibb.co/cNqJGP5) in test cases of assigning minter, admin roles (working perfect on-chain).

@UmairJanjua6 This is working fine for me when I run the tests. Might be worth us hopping on a screen share to see what steps you are taking to get this issue.

2022-01-18 12:23 UTC, UmairJanjua6 approved these changes
PR reviewed by Umair. The smart contract and unit tests are working fine.

2022-02-10 11:20 UTC, merged